### ISSUE TITLE
Include latest AWS SDK?

### ISSUE THREAD

**Issue by jplock** [lambci/node-custom-lambda#1]
What do you think about globally including the latest aws-sdk bundled with the custom runtime?

**Comment by mhart** [comment]
The intention was for this to be as minimal an implementation as possible, as every extra kb increases cold start. The aws-sdk currently weighs in at 37.5MB and 1,400 files – which is substantial.

Best practice (even on the AWS Node.js runtimes) is to include your aws-sdk as part of your function deps so that you're not caught out if something breaks in the runtime – and then use something like webpack to reduce your payload down as much as possible, only compiling into your function the pieces of aws-sdk that you're actually using.

It's possible in the future – if AWS change the way they optimize custom runtime layers and get rid of the cold start penalty – that I'd reconsider this. But for now, it's too much of a penalty to pay.
